---
title: "Resources"
output:
  html_document:
    toc_float: true
    toc: true
---

### Literature Citations
* Groeneveld E (2018) [TheSNPpit User Guide](ftp://ftp.tzv.fal.de/pub/TheSNPpit/TheSNPpit-user-guide-latest.pdf) - A high performance database system for managing large scale SNP data.
* Groeneveld E, Lichtenberg H (2016) TheSNPpit—A High Performance Database System for Managing Large Scale SNP Data. PLoS ONE 11(10): e0164043. https://doi.org/10.1371/journal.pone.0164043

### Memorandum of Understanding

Objectives of the Group:
1. __TheSNPpit Group__ serves as a platform for the maintenance of the Open Source TheSNPpit software 
2. From within __TheSNPpit Group__ programming work will be coordinated as regards bug fixes and further development of the core software as well as contributed modules.
3. __TheSNPpit Group__ will create and maintain an infrastructure for mutual support and foster discussion of ideas around TheSNPpit.

To achieve the above goals the following organizational structure will be set up:

1. According to their interests, skills, and involvement __TheSNPpit Group__ distinguishes between users, developers, and contributors.
2. The group __Coordinator__ handles the day to day issues and serves as a stopping point for communication internal and external to __TheSNPpit Group__. He further calls electronic or face to face group meetings as deemed useful. The __Coordinator__ is elected from the group of developers and contributers.
3. __Users__  run TheSNPpit software on the basis of the SNPpit release tar balls.  They want to be included in discussions around TheSNPpit, typically through a mailing list or similar media. __Users__ can sign up for this status.
4. __Developers__ are active in coding of all aspects around the TheSNPpit system, the regression tests, creation of releases, installation procedures and documentation. They get full access to the GIT repository which includes the software and the development environment.
    1. The __Software Maintainer__ is in charge of accepting modifications and new developments, integrating them into the GIT for release. The __Software Maintainer__ is elected by the group of developers.
    2. The __Developers__ address all issues around TheSNPpit code, its verification, installation, examples, and documentation. __Developers__ are accepted by the __Coordinator__ and the __Developers__ upon request and provided complete GIT access.
5. __Contributers__ support the objectives of __TheSNPpit Group__ through donations in  kind, like providing and running the GIT server, the WEB infrastructure and any other possibly financial support. Contributors can serve as references for TheSNPpit installation and incorporation into their workflow.